set -g mouse on
set -g default-terminal "screen-256color"

bind '"' split-window -c "#{pane-current-path}"
bind '%' split-window -h -c "#{pane-current-path}"

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
