### defx.nvim ###
[[plugins]]
repo = 'roxma/nvim-yarp'
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
[[plugins]]
repo = 'kristijanhusak/defx-icons'
######

### Shougo/ddc.nvim ###
[[plugins]]
repo = 'vim-denops/denops.vim'
######

### vim-airline ###
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_source = '''
    let g:airline_powerline_fonts = 1
'''
######

### vim-lsp ###
[[plugins]]
repo = 'mattn/vim-lsp-settings'
######
