### defx.nvim & deoplete.nvim ###
[[plugins]]
repo = 'roxma/nvim-yarp'
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
######

### defx.nvim ###
[[plugins]]
repo = 'kristijanhusak/defx-icons'
######

### neosnippet ###
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'Shougo/context_filetype.vim'
######

### vim-airline ###
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_source = '''
    let g:airline_powerline_fonts = 1
'''
######

### vim-lsp ###
[[plugins]]
repo = 'mattn/vim-lsp-settings'
[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_source = '''
    inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
    inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
    inoremap <expr> <cr>    pumvisible() ? "\<C-y>" : "\<cr>"
'''
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
######
