[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimfiler'
depends = ['unite.vim']
hook_add = '''
    let g:vimfiler_as_default_explorer = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    let g:airline_theme = 'molokai'
    let g:airline#extensions#tabline#enabled = 1
    nmap <C-p> <Plug>AirlineSelectPrevTab
    nmap <C-n> <Plug>AirlineSelectNextTab
'''
depends = ['vim-airline-themes']

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]]
repo = 'mattn/sonictemplate-vim'
hook_add = '''
    let g:sonictemplate_vim_template_dir = [
	\ '$HOME/.vim/template'
	\]
'''

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
    let g:winresizer_vert_resize = 1
    let g:winresizer_horiz_resize = 1
'''

[[plugins]]
repo = 'cespare/vim-toml'
